-- Python Programming Course Lessons
INSERT INTO lessons (chapter_id, title, lesson_type, content, lesson_order) VALUES 
-- Chapter 1 - Getting Started with Python
(8, 'Installing Python', 'text', '<h2>Installing Python on Your Computer</h2><p>Python is free and open-source. Download the latest version from python.org. Choose your operating system and follow the installation wizard.</p><h3>Windows Installation</h3><p>Run the installer and check "Add Python to PATH" before clicking Install Now.</p><h3>macOS Installation</h3><p>Download the macOS installer and follow the steps. Python 3 is usually pre-installed on modern Macs.</p><h3>Linux Installation</h3><p>Most Linux distributions come with Python pre-installed. Update using your package manager:</p><pre>sudo apt-get update<br>sudo apt-get install python3</pre>', 1),
(8, 'Your First Program', 'text', '<h2>Hello, World!</h2><p>Every programmer starts with "Hello, World!". In Python, its incredibly simple:</p><pre>print("Hello, World!")</pre><p>Save this in a file called hello.py and run it in your terminal:</p><pre>python hello.py</pre><p>Congratulations - you just wrote your first Python program!</p>', 2),
(8, 'Using IDLE', 'text', '<h2>Python IDLE - Integrated Development Environment</h2><p>Python comes with IDLE, a simple IDE for writing and testing code. Open IDLE by searching for "Python IDLE" in your applications.</p><h3>The Interactive Shell</h3><p>The main window is the interactive shell where you can type code and see immediate results:</p><pre>>>> 2 + 2<br>4<br>>>> print("Learning Python!")<br>Learning Python!</pre><h3>Creating Programs</h3><p>Go to File > New Window to create a new program file.</p>', 3),
-- Chapter 2 - Variables and Data Types
(9, 'What are Variables?', 'text', '<h2>Understanding Variables</h2><p>Variables are containers for storing data values. In Python, you dont need to declare the type - Python figures it out automatically.</p><pre># Creating variables<br>name = "Alice"<br>age = 25<br>height = 5.6<br><br>print(name)<br>print(age)</pre><h3>Variable Naming Rules</h3><ul><li>Must start with a letter or underscore</li><li>Can contain letters, numbers, and underscores</li><li>Case-sensitive (age and Age are different)</li></ul>', 1),
(9, 'Data Types', 'text', '<h2>Python Data Types</h2><p>Python has several built-in data types:</p><h3>Strings (str)</h3><pre>name = "Python"<br>message = ''Hello''</pre><h3>Integers (int)</h3><pre>count = 42<br>age = 25</pre><h3>Floating Point (float)</h3><pre>price = 19.99<br>pi = 3.14159</pre><h3>Booleans (bool)</h3><pre>is_active = True<br>has_license = False</pre>', 2),
(9, 'Type Conversion', 'text', '<h2>Converting Between Types</h2><p>Sometimes you need to convert from one type to another:</p><pre># String to integer<br>year = "2024"<br>year_num = int(year)<br><br># Integer to string<br>age = 25<br>age_str = str(age)<br><br># String to float<br>price = float("19.99")</pre><h3>Checking Types</h3><pre>name = "Python"<br>print(type(name))<br># Output: <class ''str''></pre>', 3),
-- Chapter 3 - Control Flow
(10, 'If Statements', 'text', '<h2>Making Decisions with If Statements</h2><p>If statements let your program make decisions:</p><pre>age = 18<br><br>if age >= 18:<br>    print("You can vote!")<br>else:<br>    print("Too young to vote.")</pre><h3>Elif for Multiple Conditions</h3><pre>score = 85<br><br>if score >= 90:<br>    grade = "A"<br>elif score >= 80:<br>    grade = "B"<br>elif score >= 70:<br>    grade = "C"<br>else:<br>    grade = "F"</pre>', 1),
(10, 'For Loops', 'text', '<h2>Repeating with For Loops</h2><p>For loops iterate over sequences:</p><pre># Loop through a range<br>for i in range(5):<br>    print(i)  # Prints 0,1,2,3,4<br><br># Loop through a list<br>fruits = ["apple", "banana", "cherry"]<br>for fruit in fruits:<br>    print(fruit)</pre><h3>Using enumerate</h3><pre>colors = ["red", "green", "blue"]<br>for index, color in enumerate(colors):<br>    print(index, color)</pre>', 2),
(10, 'While Loops', 'text', '<h2>While Loops</h2><p>While loops repeat as long as a condition is true:</p><pre>count = 0<br><br>while count < 5:<br>    print(count)<br>    count += 1<br><br>print("Done!")</pre><h3>Break and Continue</h3><pre># Break - exit the loop<br>for num in range(10):<br>    if num == 5:<br>        break<br>    print(num)<br><br># Continue - skip to next iteration<br>for num in range(5):<br>    if num == 2:<br>        continue<br>    print(num)</pre>', 3),
-- Chapter 4 - Functions
(11, 'Defining Functions', 'text', '<h2>Creating Functions</h2><p>Functions are reusable blocks of code:</p><pre>def greet():<br>    print("Hello, World!")<br><br># Call the function<br>greet()</pre><h3>Functions with Parameters</h3><pre>def greet(name):<br>    print(f"Hello, {name}!")<br><br>greet("Alice")</pre>', 1),
(11, 'Return Values', 'text', '<h2>Returning Values from Functions</h2><p>Functions can return values:</p><pre>def add(a, b):<br>    return a + b<br><br>result = add(3, 5)<br>print(result)  # Output: 8</pre><h3>Multiple Return Values</h3><pre>def calculations(a, b):<br>    return a + b, a - b, a * b<br><br>sum, diff, prod = calculations(10, 3)<br>print(sum, diff, prod)  # Output: 13 7 30</pre>', 2),
(11, 'Default Parameters', 'text', '<h2>Default Parameter Values</h2><p>You can provide default values for parameters:</p><pre>def greet(name, greeting="Hello"):<br>    print(f"{greeting}, {name}!")<br><br>greet("Alice")  # Hello, Alice!<br>greet("Bob", "Hi")  # Hi, Bob!</pre><h3>Keyword Arguments</h3><pre>def describe_pet(animal, name):<br>    print(f"{name} is a {animal}")<br><br>describe_pet(name="Max", animal="dog")</pre>', 3),
-- Chapter 5 - OOP
(12, 'Classes and Objects', 'text', '<h2>Introduction to OOP</h2><p>Object-Oriented Programming uses classes and objects:</p><pre>class Dog:<br>    def __init__(self, name, breed):<br>        self.name = name<br>        self.breed = breed<br>    <br>    def bark(self):<br>        print(f"{self.name} says Woof!")<br><br># Create an object<br>my_dog = Dog("Max", "Labrador")<br>my_dog.bark()  # Max says Woof!</pre>', 1),
(12, 'Inheritance', 'text', '<h2>Inherit from Other Classes</h2><p>Inheritance lets you create classes based on existing ones:</p><pre>class Animal:<br>    def __init__(self, name):<br>        self.name = name<br>    <br>    def speak(self):<br>        print("Some sound")<br><br>class Cat(Animal):<br>    def speak(self):<br>        print(f"{self.name} says Meow!")<br><br>class Dog(Animal):<br>    def speak(self):<br>        print(f"{self.name} says Woof!")</pre>', 2),
(12, 'Encapsulation', 'text', '<h2>Protecting Data with Encapsulation</h2><p>Use underscores to indicate private attributes:</p><pre>class BankAccount:<br>    def __init__(self, balance):<br>        self.__balance = balance  # Private<br>    <br>    def deposit(self, amount):<br>        if amount > 0:<br>            self.__balance += amount<br>    <br>    def get_balance(self):<br>        return self.__balance<br><br>account = BankAccount(1000)<br>account.deposit(500)<br>print(account.get_balance())</pre>', 3);